# Generated by Django 5.1.6 on 2025-03-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('contactno', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='skin',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('sdetails', models.CharField(max_length=100)),
                ('sprice', models.FloatField(default=0.0)),
                ('skin_image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
