# Generated by Django 5.0.7 on 2025-03-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contactno',
            new_name='c_contactno',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='emailid',
            new_name='cemailid',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='cpassword',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='skin_image',
        ),
    ]
