# Generated by Django 5.0.7 on 2025-03-13 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoapp', '0002_rename_contactno_customer_c_contactno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='skin_image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalprice', models.FloatField(default=0.0)),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valoapp.skin')),
                ('emailid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valoapp.customer')),
            ],
        ),
    ]
