# Generated by Django 5.0.7 on 2025-03-18 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoapp', '0003_skin_skin_image_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('phoneno', models.BigIntegerField()),
                ('totalbill', models.FloatField(default=0.0)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valoapp.customer')),
            ],
        ),
    ]
