# Generated by Django 5.0.7 on 2025-03-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoapp', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_bid_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skin',
            name='highest_bid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='skin',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valoapp.customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valoapp.customer')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valoapp.skin')),
            ],
        ),
    ]
