# Generated by Django 5.0.7 on 2025-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoapp', '0005_cart_is_bid_winner_skin_highest_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='bid_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
