# Generated by Django 5.0.7 on 2025-03-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoapp', '0006_skin_bid_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adminpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
